import SingleBlogCard from "@/components/SingleBlogCard";
import { getPostMetadata } from "@/lib/getPostMetadata";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hello Next App",
  description: "Generated by create next app",
};

export default function Home() {
  const postMetadata = getPostMetadata();
  const postPreviews = postMetadata.map((post) => (
    <SingleBlogCard key={post.slug} post={post} />
  ));

  return (
    <>
      <div className="mx-auto max-w-3xl">
        <h1>{postPreviews}</h1>
      </div>
    </>
  );
}
